#!/usr/bin/php
<?php

/*
 Autoload our classes as needed
*/
spl_autoload_register('clockwords_autoload');

/**
 * Function to include class files
 * @param string $class the class name we need to load
 */ 
function clockwords_autoload($class) {
  $filename = 'classes/class.'.$class.'.php';
  if (file_exists($filename)) {
    include('classes/class.'.$class.'.php');
  } else {
    dpr("Class file: ".$filename." not found");
  }
}
require_once 'dpr.php';
require_once 'constants.php';

$cwi = new cliinputs;
try {
  $wordnik = Wordnik::instance(CLOCKWORDS_WORDNIK_KEY);
  $result = $wordnik->getSuggestions('bt', 10, 0);
  dpr($result);
} catch (Exception $e) {
  dpr($e->getMessage());
}

print "\n";